version: '3.4'

services:
  chatdb:
    container_name: chatdb
    environment: 
      SA_PASSWORD: "Ebubechi89"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"

  chat.api:
    container_name: chat.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ChatConnectionString=Server=chatdb;Database=ChatDb;User Id=sa;Password=Ebubechi89;"
      - "StocksAPI:BaseUrl=http://host.docker.internal:5004/api/v1/Stocks/GetStocks"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      - chatdb
      - rabbitmq
    ports:
      - "5003:80"

  stocks.api:
    container_name: stocks.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      - rabbitmq  
    ports:
      - "5004:80"
