version: '3.4'

services:
  chatdb:
    image: mcr.microsoft.com/azure-sql-edge 

  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: src/Services/Chat/API/Dockerfile

  stocks.api:
    image: ${DOCKER_REGISTRY-}stocksapi
    build:
      context: .
      dockerfile: src/Services/Stocks/API/Dockerfile    